import type { Lesson } from './types';

// Danish touch-typing curriculum, built outward from the home row.
// Every drill uses only characters introduced in this lesson or earlier, so a
// learner never has to type a key they haven't met yet. (Verified by a test.)
export const LESSONS: Lesson[] = [
  {
    id: '1',
    level: 1,
    title: 'f og j',
    description:
      'Pegefingrenes hjemmetaster. Mærk de små kanter på F og J — derfra finder du altid hjem.',
    newChars: ['f', 'j'],
    targetWpm: 8,
    minAccuracy: 0.9,
    drills: [
      { id: '1-keys-1', kind: 'keys', text: 'fff jjj fjf jfj ffj jjf fj jf' },
      { id: '1-keys-2', kind: 'keys', text: 'jf fj jjf ffj fjfj jfjf fj jf' },
    ],
  },
  {
    id: '2',
    level: 1,
    title: 'd og k',
    description: 'Langfingrenes hjemmetaster. Hold pegefingrene på F og J.',
    newChars: ['d', 'k'],
    targetWpm: 8,
    minAccuracy: 0.9,
    drills: [
      { id: '2-keys-1', kind: 'keys', text: 'ddd kkk dkd kdk fdk jkd dk kd' },
      { id: '2-keys-2', kind: 'keys', text: 'fjdk jkdf kdjf djkf dk kd fj jk' },
    ],
  },
  {
    id: '3',
    level: 1,
    title: 's og l',
    description: 'Ringfingrenes hjemmetaster. Rækken vokser udad.',
    newChars: ['s', 'l'],
    targetWpm: 9,
    minAccuracy: 0.9,
    drills: [
      { id: '3-keys-1', kind: 'keys', text: 'sss lll sls lsl fls jsl sl ls' },
      { id: '3-keys-2', kind: 'keys', text: 'fjdksl lskdjf sldk fjsl sl ls' },
    ],
  },
  {
    id: '4',
    level: 1,
    title: 'a og æ',
    description:
      'Lillefingrenes hjemmetaster. Nu kan vi skrive de første rigtige ord!',
    newChars: ['a', 'æ'],
    targetWpm: 10,
    minAccuracy: 0.9,
    drills: [
      { id: '4-keys-1', kind: 'keys', text: 'aaa æææ aæa æaæ asdf jklæ asdf jklæ' },
      { id: '4-words-1', kind: 'words', text: 'fald skal dal kald sæl læs fad sal' },
    ],
  },
  {
    id: '5',
    level: 1,
    title: 'g og h',
    description: 'Pegefingrene strækker indad til G og H. Nu er hele hjemmerækken på plads.',
    newChars: ['g', 'h'],
    targetWpm: 10,
    minAccuracy: 0.92,
    drills: [
      { id: '5-keys-1', kind: 'keys', text: 'ggg hhh ghg hgh fgh hjg asdfg hjklæ' },
      { id: '5-words-1', kind: 'words', text: 'dag lag slag flag hals glas gas hæl' },
    ],
  },
  {
    id: '6',
    level: 1,
    title: 'Hjemmerækken — ord',
    description: 'Saml hele hjemmerækken med rigtige danske ord.',
    newChars: [],
    targetWpm: 12,
    minAccuracy: 0.92,
    drills: [
      { id: '6-words-1', kind: 'words', text: 'skal fald dag glas hals flag sæl læs' },
      { id: '6-words-2', kind: 'words', text: 'ask gas lak dal sal hæl salg flask' },
    ],
  },
  {
    id: '7',
    level: 2,
    title: 'e og i',
    description: 'Op på øverste række med langfingrene. Vokalerne åbner mange nye ord.',
    newChars: ['e', 'i'],
    targetWpm: 12,
    minAccuracy: 0.92,
    drills: [
      { id: '7-keys-1', kind: 'keys', text: 'eee iii eie iei die fie kei lei' },
      { id: '7-words-1', kind: 'words', text: 'jeg hej leg del fed side ide ged dig sig' },
    ],
  },
  {
    id: '8',
    level: 2,
    title: 'r og u',
    description: 'Pegefingrene op til R og U. Nu kan vi skrive hele sætninger.',
    newChars: ['r', 'u'],
    targetWpm: 14,
    minAccuracy: 0.93,
    drills: [
      { id: '8-keys-1', kind: 'keys', text: 'rrr uuu rur uru fru jur dru kur' },
      { id: '8-words-1', kind: 'words', text: 'rude sur kur rar gul rul frue ur' },
      { id: '8-sentence-1', kind: 'sentence', text: 'jeg er glad du er sej jeg ser dig' },
    ],
  },
  {
    id: '9',
    level: 2,
    title: 't og y',
    description:
      'Pegefingrene strækker op til T og Y. De sidste taster på øverste rækkes midte.',
    newChars: ['t', 'y'],
    targetWpm: 14,
    minAccuracy: 0.93,
    drills: [
      { id: '9-keys-1', kind: 'keys', text: 'ttt yyy tyt yty fty jyt rty uyt' },
      { id: '9-words-1', kind: 'words', text: 'tyr ret let tre fryd dyr lyd syd hyl flyt' },
      { id: '9-sentence-1', kind: 'sentence', text: 'jeg er glad du er tryg' },
    ],
  },
  {
    id: '10',
    level: 2,
    title: 'o og w',
    description: 'Ringfingrene op til W og O. Nu åbner endnu flere ord sig.',
    newChars: ['o', 'w'],
    targetWpm: 15,
    minAccuracy: 0.93,
    drills: [
      { id: '10-keys-1', kind: 'keys', text: 'ooo www owo wow tow rod sok fok' },
      { id: '10-words-1', kind: 'words', text: 'ord sol stol kold told fjord ros god ko lo' },
      { id: '10-sentence-1', kind: 'sentence', text: 'du er god og jeg er glad' },
    ],
  },
  {
    id: '11',
    level: 2,
    title: 'q og p',
    description: 'Lillefingrene strækker op til Q og P — rækkens yderpunkter.',
    newChars: ['q', 'p'],
    targetWpm: 15,
    minAccuracy: 0.93,
    drills: [
      { id: '11-keys-1', kind: 'keys', text: 'qqq ppp qpq pqp pad par qua que' },
      { id: '11-words-1', kind: 'words', text: 'pil pose post pas pris pude kop top spar april' },
      { id: '11-sentence-1', kind: 'sentence', text: 'peter har et stort kort' },
    ],
  },
  {
    id: '12',
    level: 2,
    title: 'å og ø',
    description: 'De danske vokaler Å og Ø. Højre lillefinger får travlt.',
    newChars: ['å', 'ø'],
    targetWpm: 16,
    minAccuracy: 0.92,
    drills: [
      { id: '12-keys-1', kind: 'keys', text: 'ååå øøø åøå øåø går får øre øst' },
      { id: '12-words-1', kind: 'words', text: 'på så går står får øl sø rød sød løs' },
      { id: '12-sentence-1', kind: 'sentence', text: 'du går først og jeg går sidst' },
    ],
  },
  {
    id: '13',
    level: 2,
    title: 'Øverste række — ord og sætninger',
    description: 'Saml hele øverste række med rigtige danske ord og sætninger.',
    newChars: [],
    targetWpm: 18,
    minAccuracy: 0.93,
    drills: [
      { id: '13-words-1', kind: 'words', text: 'fjord skør gæld høj tør lås pløj støj fløde stærk' },
      { id: '13-sentence-1', kind: 'sentence', text: 'jeg er glad og du er sød' },
      { id: '13-sentence-2', kind: 'sentence', text: 'håret står lige op' },
    ],
  },
  {
    id: '14',
    level: 3,
    title: 'n og m',
    description: 'Ned på nederste række. Pegefingrene rammer N og M.',
    newChars: ['n', 'm'],
    targetWpm: 16,
    minAccuracy: 0.93,
    drills: [
      { id: '14-keys-1', kind: 'keys', text: 'nnn mmm nmn mnm fan man min mon' },
      { id: '14-words-1', kind: 'words', text: 'man men min mor mod nu nem mand måne morgen' },
      { id: '14-sentence-1', kind: 'sentence', text: 'min mor er en sød mand' },
    ],
  },
  {
    id: '15',
    level: 3,
    title: 'v og b',
    description: 'Pegefingrene strækker ind til V og B.',
    newChars: ['v', 'b'],
    targetWpm: 16,
    minAccuracy: 0.93,
    drills: [
      { id: '15-keys-1', kind: 'keys', text: 'vvv bbb vbv bvb van bil bog ven' },
      { id: '15-words-1', kind: 'words', text: 'ven bil bog bo brev vand over leve liv være' },
      { id: '15-sentence-1', kind: 'sentence', text: 'vi bor ved en god vej' },
    ],
  },
  {
    id: '16',
    level: 3,
    title: 'c og komma',
    description:
      'Langfingrene ned til C og komma. Nu kan vi sætte komma i sætninger.',
    newChars: ['c', ','],
    targetWpm: 15,
    minAccuracy: 0.92,
    drills: [
      { id: '16-keys-1', kind: 'keys', text: 'ccc ,,, c,c ,c, ca, co, ce, ci,' },
      { id: '16-words-1', kind: 'words', text: 'cykel cirka cafe cola disco celle' },
      { id: '16-sentence-1', kind: 'sentence', text: 'jeg er glad, og du er sød' },
    ],
  },
  {
    id: '17',
    level: 3,
    title: 'x og punktum',
    description:
      'Ringfingrene ned til X og punktum. Sæt punktum for enden af en sætning.',
    newChars: ['x', '.'],
    targetWpm: 15,
    minAccuracy: 0.92,
    drills: [
      { id: '17-keys-1', kind: 'keys', text: 'xxx ... x.x .x. ax. ox. ex. ix.' },
      { id: '17-words-1', kind: 'words', text: 'taxa sax max boks xylofon hexe' },
      { id: '17-sentence-1', kind: 'sentence', text: 'vi tog en taxa hjem.' },
    ],
  },
  {
    id: '18',
    level: 3,
    title: 'z og bindestreg',
    description:
      'Lillefingrene ned til Z og bindestreg. Nederste række er komplet.',
    newChars: ['z', '-'],
    targetWpm: 15,
    minAccuracy: 0.92,
    drills: [
      { id: '18-keys-1', kind: 'keys', text: 'zzz --- z-z -z- za- zo- ze- zi-' },
      { id: '18-words-1', kind: 'words', text: 'zebra zone pizza jazz zoo zigzag' },
      { id: '18-sentence-1', kind: 'sentence', text: 'vi spiste pizza i går - det var godt.' },
    ],
  },
  {
    id: '19',
    level: 3,
    title: 'Hele alfabetet',
    description: 'Alle 29 bogstaver i rigtige sætninger — med komma og punktum.',
    newChars: [],
    targetWpm: 20,
    minAccuracy: 0.93,
    drills: [
      { id: '19-words-1', kind: 'words', text: 'hjælp dejlig kærlig brød smuk fjern lykke voksen' },
      {
        id: '19-sentence-1',
        kind: 'sentence',
        text: 'quizdeltagerne spiste jordbær med fløde, mens cirkusklovnen walther spillede på xylofon.',
      },
      { id: '19-sentence-2', kind: 'sentence', text: 'han bor i en stor by, men hun bor på landet.' },
    ],
  },
  {
    id: '20',
    level: 4,
    title: 'Versaler — venstre hånd',
    description:
      'Hold Skift med højre lillefinger, og skriv store bogstaver med venstre hånd.',
    newChars: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
    targetWpm: 14,
    minAccuracy: 0.92,
    drills: [
      { id: '20-keys-1', kind: 'keys', text: 'Aa Ss Dd Ff Gg Qq Ww Ee Rr Tt Zz Xx Cc Vv Bb' },
      { id: '20-words-1', kind: 'words', text: 'Anna Bo Carl David Erik Frank Gert Sara Tina Vera' },
      { id: '20-words-2', kind: 'words', text: 'Zara Xenia Walther Quist Rune' },
    ],
  },
  {
    id: '21',
    level: 4,
    title: 'Versaler — højre hånd',
    description:
      'Hold Skift med venstre lillefinger, og skriv store bogstaver med højre hånd.',
    newChars: ['Y', 'U', 'I', 'O', 'P', 'Å', 'H', 'J', 'K', 'L', 'Æ', 'Ø', 'N', 'M'],
    targetWpm: 14,
    minAccuracy: 0.92,
    drills: [
      { id: '21-keys-1', kind: 'keys', text: 'Hh Jj Kk Ll Yy Uu Ii Oo Pp Nn Mm Åå Øø Ææ' },
      { id: '21-words-1', kind: 'words', text: 'Hans Ida Jens Kira Lars Mette Niels Ole Pia Ulla' },
      { id: '21-words-2', kind: 'words', text: 'Åse Ørsted Ærø Møn Yrsa' },
    ],
  },
  {
    id: '22',
    level: 4,
    title: 'Versaler i sætninger',
    description: 'Store bogstaver i sætninger — navne og sætningsstart.',
    newChars: [],
    targetWpm: 18,
    minAccuracy: 0.93,
    drills: [
      { id: '22-sentence-1', kind: 'sentence', text: 'Jeg hedder Anna og jeg bor i Aarhus.' },
      { id: '22-sentence-2', kind: 'sentence', text: 'Min ven Erik spiller fodbold hver dag.' },
      { id: '22-sentence-3', kind: 'sentence', text: 'København er en stor by i Danmark.' },
    ],
  },
  {
    id: '23',
    level: 5,
    title: 'Tallene 4 5 6 7',
    description: 'Talrækken begynder. Pegefingrene rammer 4, 5, 6 og 7.',
    newChars: ['4', '5', '6', '7'],
    targetWpm: 12,
    minAccuracy: 0.9,
    drills: [
      { id: '23-keys-1', kind: 'keys', text: '444 555 666 777 456 567 4567 7654' },
      { id: '23-keys-2', kind: 'keys', text: 'ff44 jj77 dd55 kk66 f4j7 d5k6' },
      { id: '23-sentence-1', kind: 'sentence', text: 'Klokken er 5 og 6 og 7.' },
    ],
  },
  {
    id: '24',
    level: 5,
    title: 'Tallene 3 8 2 9',
    description: 'Lang- og ringfingrene op til 3, 8, 2 og 9.',
    newChars: ['3', '8', '2', '9'],
    targetWpm: 12,
    minAccuracy: 0.9,
    drills: [
      { id: '24-keys-1', kind: 'keys', text: '333 888 222 999 38 83 29 92 2389' },
      { id: '24-keys-2', kind: 'keys', text: 'dd33 kk88 ss22 ll99 d3k8 s2l9' },
      { id: '24-sentence-1', kind: 'sentence', text: 'Vi er 8 i klassen og 2 er syge.' },
    ],
  },
  {
    id: '25',
    level: 5,
    title: 'Tallene 1 0 og +',
    description: 'Lillefingrene op til 1 og 0 — og plus-tasten.',
    newChars: ['1', '0', '+'],
    targetWpm: 12,
    minAccuracy: 0.9,
    drills: [
      { id: '25-keys-1', kind: 'keys', text: '111 000 +++ 10 01 100 010 1+0 0+1' },
      { id: '25-keys-2', kind: 'keys', text: 'aa11 1+1 0+0 100 1010 10+10' },
      { id: '25-sentence-1', kind: 'sentence', text: 'Jeg har 10 fingre og 10 tæer.' },
      { id: '25-sentence-2', kind: 'sentence', text: '1 + 1 er 2 og 2 + 2 er 4.' },
    ],
  },
  {
    id: '26',
    level: 5,
    title: 'Tal i tekst',
    description: 'Bland tal og ord, som du gør det i hverdagen.',
    newChars: [],
    targetWpm: 16,
    minAccuracy: 0.92,
    drills: [
      { id: '26-keys-1', kind: 'keys', text: '10 20 30 40 50 60 70 80 90 100' },
      { id: '26-sentence-1', kind: 'sentence', text: 'Der er 365 dage i et år.' },
      { id: '26-sentence-2', kind: 'sentence', text: 'Vi mødtes klokken 8 og spiste klokken 9.' },
    ],
  },
  {
    id: '27',
    level: 6,
    title: 'Kolon, semikolon og co.',
    description:
      'Tegnsætning: kolon, semikolon, understreg, apostrof og stjerne.',
    newChars: [':', ';', '_', "'", '*'],
    targetWpm: 10,
    minAccuracy: 0.9,
    drills: [
      { id: '27-keys-1', kind: 'keys', text: 'a: o; e_ i* u: :; _* :: ;; **' },
      { id: '27-keys-2', kind: 'keys', text: "fil_navn 3*4 det' her' klokken_5" },
      { id: '27-sentence-1', kind: 'sentence', text: 'Klokken er 12:30; vi ses.' },
      { id: '27-sentence-2', kind: 'sentence', text: 'Jeg kom; du gik: vi mødtes.' },
    ],
  },
  {
    id: '28',
    level: 6,
    title: 'Udråb og spørgsmål',
    description: 'Udråbstegn og spørgsmålstegn — giv sætningen liv.',
    newChars: ['!', '?'],
    targetWpm: 12,
    minAccuracy: 0.9,
    drills: [
      { id: '28-keys-1', kind: 'keys', text: 'ja! nej! hvad? hvor? !! ?? !? ?!' },
      { id: '28-sentence-1', kind: 'sentence', text: 'Hej! Hvordan går det?' },
      { id: '28-sentence-2', kind: 'sentence', text: 'Er du klar? Ja, jeg er klar!' },
    ],
  },
  {
    id: '29',
    level: 6,
    title: 'Parenteser og citationstegn',
    description: 'Parenteser, skråstreg, lighedstegn og citationstegn.',
    newChars: ['(', ')', '/', '=', '"'],
    targetWpm: 10,
    minAccuracy: 0.9,
    drills: [
      { id: '29-keys-1', kind: 'keys', text: '(a) (b) 7/8 2=2 "ja" () // == ""' },
      { id: '29-sentence-1', kind: 'sentence', text: '2 + 2 = 4 (det er let).' },
      { id: '29-sentence-2', kind: 'sentence', text: 'Hun sagde "hej" og smilede.' },
    ],
  },
  {
    id: '30',
    level: 6,
    title: 'De sidste tegn',
    description: 'De sidste tegn: #, ¤, %, &, ½, §, < og >.',
    newChars: ['#', '¤', '%', '&', '½', '§', '<', '>'],
    targetWpm: 8,
    minAccuracy: 0.9,
    drills: [
      { id: '30-keys-1', kind: 'keys', text: '## ¤¤ %% && ½½ §§ << >> #5 50% a&b 5<6 6>5' },
      { id: '30-sentence-1', kind: 'sentence', text: 'Tilbud: 50% i dag & i morgen!' },
      { id: '30-sentence-2', kind: 'sentence', text: 'Se § 4, køb ½ liter til værelse #2 for 99 ¤.' },
    ],
  },
  {
    id: '31',
    level: 6,
    title: 'Hele tastaturet',
    description: 'Bogstaver, tal og tegn i ét — alt hvad du har lært.',
    newChars: [],
    targetWpm: 18,
    minAccuracy: 0.92,
    drills: [
      {
        id: '31-sentence-1',
        kind: 'sentence',
        text: 'Quizdeltagerne spiste jordbær med fløde, mens cirkusklovnen Walther spillede på xylofon!',
      },
      { id: '31-sentence-2', kind: 'sentence', text: 'Bestil 3 pizzaer (50% rabat) inden kl. 18:30!' },
      { id: '31-sentence-3', kind: 'sentence', text: 'Pris: 199 kr. = 2 stk. & gratis fragt!' },
    ],
  },
];

const byId = new Map(LESSONS.map((lesson) => [lesson.id, lesson]));

export function getLesson(id: string | undefined): Lesson | undefined {
  return id === undefined ? undefined : byId.get(id);
}

/** The lesson after the given id, or undefined if it's the last one. */
export function getNextLesson(id: string): Lesson | undefined {
  const index = LESSONS.findIndex((lesson) => lesson.id === id);
  return index === -1 ? undefined : LESSONS[index + 1];
}
